name: License Check
on:
  push:
    branches:
      - trying
      - staging
  pull_request:
    branches: [ main ]
  merge_group:
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install license-header-checker
        run: curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash -s v1.3.0
      - name: Run license check
        run: ./bin/license-header-checker -a -r  ./license_header.txt . cc h
